wms_backend:
    resource: "@WMSBackendBundle/Controller/"
    type:     annotation
    prefix:   /

_front:
    resource: routing/front.yml

_admin:
    resource: routing/admin.yml
    prefix:   /backend
